project_oauth/models.py
from flask_login import UserMixin
from werkzeug.security import generate_password_hash, check_password_hash

from project_oauth.extensions import db


class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(20), unique=True, index=True)
    password_hash = db.Column(db.String(128))
    locale = db.Column(db.String(20))

    def set_password(self, password):
        self.password_hash = generate_password_hash(password)

    def validate_password(self, password):
        return check_password_hash(self.password_hash, password)

project_oauth/__init__.py
import os
import click
from flask import Flask
from project_oauth.apis.v1 import api_v1
from project_oauth.settings import config, basedir
from project_oauth.extensions import db, login_manager, csrf
from project_oauth.blueprints.auth import auth_bp



def create_app(config_name=None):
    if config_name is None:
        config_name = os.getenv('FLASK_CONFIG', 'development')

    app = Flask('project_oauth')
    app.config.from_object(config[config_name])

    register_extensions(app)
    register_blueprints(app)
    register_commands(app)
    register_errors(app)
    register_template_context(app)
    return app

def register_extensions(app):
    db.init_app(app)
    login_manager.init_app(app)
    csrf.init_app(app)
    csrf.exempt(api_v1)


def register_blueprints(app):
    app.register_blueprint(api_v1, url_prefix='/api/v1')
    app.register_blueprint(api_v1, subdomain='api', url_prefix='/v1')
    app.register_blueprint(auth_bp)

def register_commands(app):
    @app.cli.command()
    @click.option('--drop', is_flag=True, help='Create after drop.')
    def initdb(drop):
        """Initialize the database."""
        if drop:
            click.confirm('This operation will delete the database, do you want to continue?', abort=True)
            db.drop_all()
            click.echo('Drop tables.')
        db.create_all()
        click.echo('Initialized database.')

def register_errors(app):
    pass

def register_template_context(app):
    pass

project_oauth/apis/v1/__init__.py
from flask import Blueprint, jsonify
from flask_cors import CORS

api_v1 = Blueprint('api_v1', __name__)

CORS(api_v1)


from project_oauth.apis.v1 import resources

project_oauth/apis/v1/auth.py
from flask import g, current_app, request
from itsdangerous import TimedJSONWebSignatureSerializer as Serializer, BadSignature, SignatureExpired
from project_oauth.apis.v1.errors import api_abort, invalid_token, token_missing
from project_oauth.models import User

from functools import wraps

def generate_token(user):
    expiration = 3600
    s = Serializer(current_app.config['SECRET_KEY'], expires_in=expiration)
    token = s.dumps({'id': user.id}).decode('ascii')
    return token, expiration

def validate_token(token):
    s = Serializer(current_app.config['SECRET_KEY'])
    try:
        data = s.loads(token)
    except (BadSignature, SignatureExpired):
        return False
    user = User.query.get(data['id'])
    if user is None:
        return False
    g.current_user = user
    return True

def get_token():
    # Flask/Werkzeug do not recognize any authentication types
    # other than Basic or Digest, so here we parse the header by hand.
    if 'Authorization' in request.headers:
        try:
            token_type, token = request.headers['Authorization'].split(None, 1)
        except ValueError:
            # The Authorization header is either empty or has no token
            token_type = token = None
    else:
        token_type = token = None

    return token_type, token

def auth_required(f):
    @wraps(f)
    def decorated(*args, **kwargs):
        token_type, token = get_token()
        if request.method != 'OPTIONS':
            if token_type is None or token_type.lower() != 'bearer':
                return api_abort(400, 'The token type must be bearer.')
            if token is None:
                return token_missing()
            if not validate_token(token):
                return invalid_token()
        return f(*args, **kwargs)
    return decorated

project_oauth/blueprints/auth.py
from faker import Faker
from flask import render_template, redirect, url_for, Blueprint, request, jsonify
from flask_login import login_user, logout_user, current_user

from project_oauth.extensions import db
from project_oauth.models import User

auth_bp = Blueprint('auth', __name__)
fake = Faker()


@auth_bp.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('todo.app'))

    if request.method == 'POST':
        data = request.get_json()
        username = data['username']
        password = data['password']

        user = User.query.filter_by(username=username).first()

        if user is not None and user.validate_password(password):
            login_user(user)
            return jsonify(message=_('Login success.'))
        return jsonify(message=_('Invalid username or password.')), 400
    return render_template('_login.html')



@auth_bp.route('/register')
def register():
    # generate a random account for demo use
    username = fake.user_name()
    # make sure the generated username was not in database
    while User.query.filter_by(username=username).first() is not None:
        username = fake.user_name()
    password = fake.word()
    user = User(username=username)
    user.set_password(password)
    db.session.add(user)
    db.session.commit()

    return jsonify(username=username, password=password, message='Generate success.')

project_oauth/templates/_app.html
{% extends 'base.html' %}

{% block content %}
    <header class="row">
        <input id="item-input" data-href="{{ url_for('.new_item') }}"
               type="text" placeholder="{{ _('What needs to be done?') }}" autocomplete="off" autofocus required>
    </header>
    <div class="row" id="dashboard">
        <div class="col l9 m12 s12">
            <ul class="tabs">
                <li class="tab col m4 s12">
                    <a class="blue-text button" id="all-item">
                        {{ _('All') }} <span class="grey-text small-text" id="all-count">{{ all_count }}</span>
                    </a>
                </li>
                <li class="tab col m4 s12">
                    <a class="blue-text button" id="active-item">
                        {{ _('Active') }} <span class="grey-text small-text" id="active-count">{{ active_count }}</span>
                    </a>
                </li>
                <li class="tab col m4 s12">
                    <a class="blue-text button" id="completed-item">
                        {{ _('Done') }} <span class="grey-text small-text"
                                              id="completed-count">{{ completed_count }}</span>
                    </a>
                </li>
            </ul>
        </div>
        <div class="col l3 hide-on-med-and-down">
            <a class="waves-effect waves-light btn red right" id="clear-btn">
                <i class="material-icons left">clear_all</i>Clear
            </a>
        </div>
    </div>

    <div class="items">
        {% for item in items %}
            {% include '_item.html' %}
        {% endfor %}
    </div>
{% endblock %}

project_oauth/templates/_intro.html
{% extends 'base.html' %}

{% block content %}
    <div class="center">
        <h2 class="teal-text text-lighten-2">Todoism</h2>
        <h5 class="light">{{ _('We are todoist, we use todoism.') }}</h5>
        <div class="row center-block">
            <div class="fake-browser-ui hoverable card-panel">
                <div class="frame">
                    <span class="red"></span>
                    <span class="blue"></span>
                    <span class="orange"></span>
                </div>
                <img class="responsive-img" src="{{ url_for('static', filename=_('demo.png')) }}">
            </div>
        </div>
        <div class="row">
            <a href="#login" class="btn waves-effect waves-light red">{{ _('Get Started') }}</a>
        </div>
    </div>
{% endblock %}

project_oauth/templates/_item.html
<div class="row item card-panel hoverable" data-href="{{ url_for('.edit_item', item_id=item.id) }}"
     data-id="{{ item.id }}" data-body="{{ item.body }}" data-done={{ item.done|tojson }}>
    <span class="item-body">
        <a class="button done-btn" data-href="{{ url_for('.toggle_item', item_id=item.id) }}">
            <i class="material-icons left">{% if item.done %}check_box{% else %}check_box_outline_blank{% endif %}</i>
        </a>
        <span class="{% if item.done %}inactive-item{% else %}active-item{% endif %}"
              id="body{{ item.id }}">{{ item.body }}</span>
    </span>
    <span class="hide edit-btns right">
        <a class="right button delete-btn" data-href="{{ url_for('.delete_item', item_id=item.id) }}">
            <i class="material-icons small-icon left">clear</i>
        </a>
        <a class="right button edit-btn">
            <i class="material-icons small-icon left">mode_edit</i>
        </a>
    </span>
</div>

project_oauth/templates/_login.html
{% extends 'base.html' %}

{% block content %}
    <header class="center">
        <h4 class="red-text">{{ _('Login on Todoism') }}</h4><br>
    </header>
    <div class="login-form">
        <input class="validate login-input" id="username-input" name="username" type="text" placeholder="Username"
               autofocus required>
        <input class="validate login-input" id="password-input" name="password" type="password" placeholder="Password"
               required>
        <span class="right">
            <a class="btn grey" id="register-btn">{{ _('Get a test account') }}</a>
            <a class="btn red" id="login-btn">{{ _('Login') }}</a>
        </span>
        <p><a class="blue-text link button left" id="toggle-password">{{ _('Toggle Password') }}</a></p>&nbsp;
    </div>
{% endblock %}

project_oauth/templates/base.html
<nav class="green lighten-2" role="navigation">
    <div class="nav-wrapper container">
        <a href="#intro" class="brand-logo">Todoism</a>
        <a data-target="nav-mobile" class="sidenav-trigger button"><i class="material-icons">menu</i></a>
        <ul class="right hide-on-med-and-down">
            {% if current_user.is_authenticated %}
                <li>
                    <a class="waves-effect waves-light btn orange" href="#app">{{ current_user.username }}
                        <span class="badge new" id="active-count-nav">{{ active_items }}</span>
                    </a>
                </li>
                <li>
                    <a class="waves-effect waves-light" id="logout-btn" data-href="{{ url_for('auth.logout') }}">
                        <i class="material-icons">power_settings_new</i>
                    </a>
                </li>
            {% else %}
                <li><a class="waves-effect waves-light btn red" href="#login">{{ _('Login') }}</a></li>
            {% endif %}
            <li>
                <a class="waves-effect waves-light dropdown-trigger" id="locale-dropdown-btn" data-target="locale-dropdown">
                    <i class="material-icons">language</i>
                </a>
            </li>
        </ul>
    </div>
</nav>

<ul id="nav-mobile" class="sidenav">
    {% if current_user.is_authenticated %}
        <li><a class="waves-effect waves-light btn red clear-btn sidenav-close">Clear</a></li>
        <li><a class="waves-effect waves-light btn orange sidenav-close" id="app-btn"
               href="#app">{{ current_user.username }}</a>
        </li>
        <li><a class="waves-effect waves-light btn grey sidenav-close" id="logout-btn"
               data-href="{{ url_for('auth.logout') }}">{{ _('Logout') }}</a></li>
    {% else %}
        <li><a class="waves-effect waves-light btn red sidenav-close" href="#login">{{ _('Login') }}</a></li>
    {% endif %}
</ul>

<ul id="locale-dropdown" class="dropdown-content">
    <li><a class="lang-btn" data-href="{{ url_for('home.set_locale', locale='zh_Hans_CN') }}">简体中文</a></li>
    <li><a class="lang-btn" data-href="{{ url_for('home.set_locale', locale='en_US') }}">English</a></li>
</ul>

<main>
    {% block content %}{% endblock %}
</main>
<footer class="center">
    <small> &copy; 2018 <a class="blue-text link" href="http://greyli.com" title="Written by Grey Li">Grey Li</a> -
        <a class="blue-text link" href="https://github.com/greyli/todoism" title="Fork me on GitHub">GitHub</a> -
        <a class="blue-text link" href="http://helloflask.com" title="A HelloFlask project">HelloFlask</a>
    </small>
</footer>

project_oauth/templates/errors.html
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <meta charset="utf-8"/>
    <title>Error {{ code }} - Todoism</title>
    <link href="{{ url_for('static', filename='css/materialize.min.css') }}" rel="stylesheet">
    <link href="{{ url_for('static', filename='css/style.css') }}" rel="stylesheet">
    <link rel="icon" href="{{ url_for('static', filename='favicon.ico') }}" type="image/x-icon">
</head>

<body>
<main>
    <header class="center">
        <h4 class="red-text">Todoism</h4>
    </header>
    <div class="row card-panel hoverable">
        <span class="col s10">
            <span class="active-item">{{ code }} - {{ info }}</span>
        </span>
        <span class="col s2">
            <a class="button right" href="{{ url_for('home.index') }}">{{ _('Back Home') }}</a>
        </span>
    </div>
</main>
</body>
</html>

project_oauth/templates/index.html
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <meta charset="utf-8"/>
    <title>Todoism</title>
    <link href="{{ url_for('static', filename='css/materialize.min.css') }}" rel="stylesheet">
    <link href="{{ url_for('static', filename='css/style.css') }}" rel="stylesheet">
    <link rel="icon" href="{{ url_for('static', filename='favicon.ico') }}" type="image/x-icon">
    <link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
</head>
<body>
<div id="main"></div>
<script src="{{ url_for('static', filename='js/jquery.min.js') }}"></script>
<script src="{{ url_for('static', filename='js/materialize.min.js') }}"></script>
<script src="{{ url_for('static', filename='js/script.js') }}" type="text/javascript"></script>
<script type="text/javascript">
    var csrf_token = "{{ csrf_token() }}";
    var login_page_url = "{{ url_for('auth.login') }}";
    var app_page_url = "{{ url_for('todo.app') }}";
    var intro_page_url = "{{ url_for('home.intro') }}";
    var new_item_url = "{{ url_for('todo.new_item') }}";
    var clear_item_url = "{{ url_for('todo.clear_items') }}";
    var login_url = "{{ url_for('auth.login') }}";
    var register_url = "{{ url_for('auth.register') }}";
    var logout_url = "{{ url_for('auth.logout') }}";
    var default_error_message = "{{ _('Oops, something was wrong!') }}";
    var empty_body_error_message = "{{ _('Your todo was empty!') }}";
    var login_error_message = "{{ _('Empty username or password!') }}";
</script>
</body>
</html>